# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: vmagent
version: "v0.2.0"
slug: vmagent
description: Collect Home Assistant prometheus metrics and store them to remote systems via remote_write protocol.
init: false
map:
  - share:rw
arch:
  - aarch64
  - armv7
  - armhf
  - amd64
  - i386
options:
  remoteWriteUrl: ""
  remoteWriteUsername: ""
  remoteWritePassword: ""
  prometheusScrapeHTTPS: false
  prometheusScrapeInterval: "20s"
  prometheusScrapeTimeout: "15s"
  prometheusStaticLabels: []
  longelivedToken: ""
  homeassistantUrl: ""
schema:
  remoteWriteUrl: "str"
  remoteWriteUsername: "password?"
  remoteWritePassword: "password?"
  prometheusScrapeHTTPS: bool
  prometheusScrapeInterval: "str?"
  prometheusScrapeTimeout: "str?"
  prometheusStaticLabels:
    - key: "str"
      value: "str"
  longelivedToken: "password"
  homeassistantUrl: "str"